export const initialValues = {
  country: '',
  description: '',
  id: null,
  imageUrls: null,
  locality: '',
  logo: null,
  rating: 0,
  room: {
    title: '',
    singleRoom: false,
    doubleRoom: false,
    queenRoom: false,
    singleRoomTotal: '',
    doubleRoomTotal: '',
    queenRoomTotal: '',
    singleRoomAvailable: '',
    doubleRoomAvailable: '',
    queenRoomAvailable: '',
  },
  rooms: [],
  title: '',
  type: '',
}
